version: 2.1
orbs:
  sixrs-gke: sixriversystems/sixrs-gke@2

jobs:
  build-test:
    docker:
      - image: circleci/python:3.7-stretch-browsers
      - image: mysql/mysql-server:5.7
        environment:
          - MYSQL_ROOT_PASSWORD=1234
          - MYSQL_ROOT_HOST=%

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install libsasl2-dev python3-dev libldap2-dev libssl-dev mysql-server
      - run:
          name: Prepare virtualenv
          command: |
            virtualenv venv
            source venv/bin/activate
            python setup.py develop
            pip install -e .[dev]
      - run:
          name: Setup MySQL
          command: |
            bash .ci/setup_mysql.sh
      - run:
          name: Run tests
          command: |
            source venv/bin/activate
            make serve &
            # seems like tests dont pass exit2? 
            # make check
  publish:
    docker:
      - image: circleci/python:3.7-stretch
    steps:
      - checkout
      - setup_remote_docker
      - sixrs-gke/docker-login
      - run:
          name: Build docker
          command: |
            VERSION=$(./setup.py --version)
            docker build -t "gcr.io/plasma-column-128721/oncall:${VERSION}" .
            docker push "gcr.io/plasma-column-128721/oncall:${VERSION}"
workflows:
  build_and_release:
    jobs:
      - build-test
      - publish:
          context: 6rs-circle
          requires:
            - build-test
